import { CiRoute } from "react-icons/ci";
import {
  FaBook,
  FaBrain,
  FaCamera,
  FaChess,
  FaCircle,
  FaCompactDisc,
  FaHands,
  FaMicrophone,
  FaMusic,
  FaPalette,
  FaPenNib,
  FaTheaterMasks,
} from "react-icons/fa";
import {
  FaBookOpen,
  FaCircleDot,
  FaHandsClapping,
  FaMasksTheater,
  FaMicrophoneLines,
  FaPaintbrush,
  FaScissors,
} from "react-icons/fa6";
import {
  GiCeremonialMask,
  GiCricketBat,
  GiDart,
  GiHighKick,
  GiHighPunch,
  GiKnot,
  GiMicrophone,
  GiMusicalNotes,
  GiMusicSpell,
  GiRun,
  GiShuttlecock,
  GiSoccerBall,
  GiSprint,
  GiTargetShot,
  GiVolleyballBall,
} from "react-icons/gi";
import { IoIosMicrophone } from "react-icons/io";
import {
  IoFootsteps,
  IoPencil,
  IoSparklesSharp,
  IoTabletLandscape,
} from "react-icons/io5";
import { MdGroups2, MdQuiz, MdSportsKabaddi } from "react-icons/md";

export const individualGames = {
  sports: [
    {
      id: "IE001",
      name: "100m Sprint",
      icon: IoFootsteps,
      category: "Athletics",
    },
    {
      id: "IE002",
      name: "200m Sprint",
      icon: GiRun,
      category: "Athletics",
    },
    {
      id: "IE003",
      name: "400m Race",
      icon: GiRun,
      category: "Athletics",
    },
    {
      id: "IE004",
      name: "800m Race",
      icon: GiSprint,
      category: "Athletics",
    },
    {
      id: "IE005",
      name: "1500m Race",
      icon: GiSprint,
      category: "Athletics",
    },
    { id: "IE006", name: "5K Run", icon: CiRoute, category: "Athletics" },
    {
      id: "IE007",
      name: "Long Jump",
      icon: GiHighPunch,
      category: "Athletics",
    },
    {
      id: "IE008",
      name: "High Jump",
      icon: GiHighKick,
      category: "Athletics",
    },
    {
      id: "IE009",
      name: "Shot Put",
      icon: FaCircleDot,
      category: "Athletics",
    },
    {
      id: "IE010",
      name: "Discus Throw",
      icon: FaCompactDisc,
      category: "Athletics",
    },
    {
      id: "IE011",
      name: "Javelin Throw",
      icon: GiTargetShot,
      category: "Athletics",
    },
    {
      id: "IE012",
      name: "Chess",
      icon: FaChess,
      category: "Indoor Sports",
    },
    {
      id: "IE013",
      name: "Carrom Singles",
      icon: FaCircle,
      category: "Indoor Sports",
    },
    {
      id: "IE014",
      name: "Table Tennis Singles",
      icon: IoTabletLandscape,
      category: "Indoor Sports",
    },
    {
      id: "IE015",
      name: "Badminton Singles",
      icon: GiShuttlecock,
      category: "Indoor Sports",
    },
    {
      id: "IE016",
      name: "Darts",
      icon: GiDart,
      category: "Indoor Sports",
    },
  ],

  arts: [
    {
      id: "IE023",
      name: "Solo Singing (Malayalam)",
      icon: FaMicrophone,
      category: "Music",
    },
    {
      id: "IE024",
      name: "Solo Singing (Hindi)",
      icon: FaMicrophone,
      category: "Music",
    },
    {
      id: "IE025",
      name: "Solo Singing (English)",
      icon: FaMicrophone,
      category: "Music",
    },
    {
      id: "IE026",
      name: "Instrumental Solo",
      icon: FaMusic,
      category: "Music",
    },
    {
      id: "IE027",
      name: "Solo Dance (Free Style)",
      icon: GiMusicSpell,
      category: "Dance",
    },
    {
      id: "IE028",
      name: "Classical Dance",
      icon: GiMusicSpell,
      category: "Dance",
    },
    {
      id: "IE029",
      name: "Folk Dance Solo",
      icon: GiMusicSpell,
      category: "Dance",
    },
    {
      id: "IE030",
      name: "Elocution (Malayalam)",
      icon: FaBookOpen,
      category: "Literary",
    },
    {
      id: "IE031",
      name: "Elocution (English)",
      icon: FaBookOpen,
      category: "Literary",
    },
    {
      id: "IE032",
      name: "Storytelling",
      icon: FaMicrophoneLines,
      category: "Literary",
    },
    {
      id: "IE033",
      name: "Poetry Writing",
      icon: FaPenNib,
      category: "Literary",
    },
    {
      id: "IE034",
      name: "Essay Writing",
      icon: FaBook,
      category: "Literary",
    },
    {
      id: "IE035",
      name: "Quiz (Individual)",
      icon: FaBrain,
      category: "Literary",
    },
    {
      id: "IE036",
      name: "Pencil Drawing",
      icon: IoPencil,
      category: "Creative Arts",
    },
    {
      id: "IE037",
      name: "Painting",
      icon: FaPalette,
      category: "Creative Arts",
    },
    {
      id: "IE038",
      name: "Photography",
      icon: FaCamera,
      category: "Creative Arts",
    },
    {
      id: "IE039",
      name: "Digital Art",
      icon: FaPaintbrush,
      category: "Creative Arts",
    },
    {
      id: "IE040",
      name: "Craft Making",
      icon: FaScissors,
      category: "Creative Arts",
    },
    {
      id: "IE041",
      name: "Mehendi",
      icon: IoSparklesSharp,
      category: "Creative Arts",
    },
  ],
};

export const groupGames = {
  sports: [
    {
      id: "GE001",
      name: "Football",
      icon: GiSoccerBall,
      category: "Team Sports",
    },
    {
      id: "GE002",
      name: "Cricket",
      icon: GiCricketBat,
      category: "Team Sports",
    },
    {
      id: "GE003",
      name: "Volleyball",
      icon: GiVolleyballBall,
      category: "Team Sports",
    },
    {
      id: "GE004",
      name: "Kabaddi",
      icon: MdSportsKabaddi,
      category: "Team Sports",
    },
    {
      id: "GE005",
      name: "Tug of War",
      icon: GiKnot,
      category: "Team Sports",
    },
    {
      id: "GE006",
      name: "Badminton Doubles",
      icon: GiShuttlecock,
      category: "Racket Sports",
    },
    {
      id: "GE007",
      name: "Table Tennis Doubles",
      icon: IoTabletLandscape,
      category: "Racket Sports",
    },
    {
      id: "GE008",
      name: "Carrom Doubles",
      icon: FaCircle,
      category: "Indoor Sports",
    },
  ],

  arts: [
    {
      id: "GE009",
      name: "Group Song (Malayalam)",
      icon: GiMicrophone,
      category: "Music",
    },
    {
      id: "GE010",
      name: "Group Song (Hindi)",
      icon: GiMicrophone,
      category: "Music",
    },
    {
      id: "GE011",
      name: "Group Song (English)",
      icon: GiMicrophone,
      category: "Music",
    },
    {
      id: "GE012",
      name: "Choir",
      icon: IoIosMicrophone,
      category: "Music",
    },
    {
      id: "GE013",
      name: "Group Dance",
      icon: GiMusicalNotes,
      category: "Dance",
    },
    {
      id: "GE014",
      name: "Folk Dance Group",
      icon: GiMusicalNotes,
      category: "Dance",
    },
    {
      id: "GE015",
      name: "Oppana",
      icon: FaHandsClapping,
      category: "Dance",
    },
    {
      id: "GE016",
      name: "Margamkali",
      icon: FaHands,
      category: "Dance",
    },
    {
      id: "GE017",
      name: "Mime",
      icon: FaTheaterMasks,
      category: "Stage Performance",
    },
    {
      id: "GE018",
      name: "Skit",
      icon: FaMasksTheater,
      category: "Stage Performance",
    },
    {
      id: "GE019",
      name: "Drama",
      icon: GiCeremonialMask,
      category: "Stage Performance",
    },
    {
      id: "GE020",
      name: "Quiz (Team)",
      icon: MdQuiz,
      category: "Literary",
    },
    {
      id: "GE021",
      name: "Debate",
      icon: MdGroups2,
      category: "Literary",
    },
  ],
};

export const Games = [
  {
    _id: "IE001",
    name: "100m Sprint",
    category: "Sports",
    type: "Individual",
    icon: "IoFootsteps",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE002",
    name: "200m Sprint",
    category: "Sports",
    type: "Individual",
    icon: "GiRun",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE003",
    name: "400m Race",
    category: "Sports",
    type: "Individual",
    icon: "GiRun",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE004",
    name: "Long Jump",
    category: "Sports",
    type: "Individual",
    icon: "GiHighPunch",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE005",
    name: "Chess",
    category: "Sports",
    type: "Individual",
    icon: "FaChess",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },

  {
    _id: "IE023",
    name: "Solo Singing (Malayalam)",
    category: "Arts",
    type: "Individual",
    icon: "FaMicrophone",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE024",
    name: "Instrumental Solo",
    category: "Arts",
    type: "Individual",
    icon: "FaMusic",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE025",
    name: "Solo Dance (Free Style)",
    category: "Arts",
    type: "Individual",
    icon: "GiMusicSpell",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE026",
    name: "Photography",
    category: "Arts",
    type: "Individual",
    icon: "FaCamera",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },
  {
    _id: "IE027",
    name: "Quiz (Individual)",
    category: "Arts",
    type: "Individual",
    icon: "FaBrain",
    maxParticipants: 1,
    maxTeamsPerCompetitionTeam: 1,
    isActive: true,
  },

  {
    _id: "GE001",
    name: "Football",
    category: "Sports",
    type: "Group",
    icon: "GiSoccerBall",
    maxParticipants: 11,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE002",
    name: "Cricket",
    category: "Sports",
    type: "Group",
    icon: "GiCricketBat",
    maxParticipants: 11,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE003",
    name: "Volleyball",
    category: "Sports",
    type: "Group",
    icon: "GiVolleyballBall",
    maxParticipants: 6,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE004",
    name: "Kabaddi",
    category: "Sports",
    type: "Group",
    icon: "MdSportsKabaddi",
    maxParticipants: 7,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE005",
    name: "Tug of War",
    category: "Sports",
    type: "Group",
    icon: "GiKnot",
    maxParticipants: 8,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },

  {
    _id: "GE009",
    name: "Group Song (Malayalam)",
    category: "Arts",
    type: "Group",
    icon: "GiMicrophone",
    maxParticipants: 8,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE010",
    name: "Choir",
    category: "Arts",
    type: "Group",
    icon: "IoIosMicrophone",
    maxParticipants: 15,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE011",
    name: "Group Dance",
    category: "Arts",
    type: "Group",
    icon: "GiMusicalNotes",
    maxParticipants: 10,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE012",
    name: "Mime",
    category: "Arts",
    type: "Group",
    icon: "FaTheaterMasks",
    maxParticipants: 8,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
  {
    _id: "GE013",
    name: "Quiz (Team)",
    category: "Arts",
    type: "Group",
    icon: "MdQuiz",
    maxParticipants: 4,
    maxTeamsPerCompetitionTeam: 3,
    isActive: true,
  },
];
