import { BsCameraReelsFill } from "react-icons/bs";
import { CiRoute } from "react-icons/ci";
import {
  FaBook,
  FaBrain,
  FaCamera,
  FaChess,
  FaCircle,
  FaCompactDisc,
  FaHands,
  FaMicrophone,
  FaMusic,
  FaPalette,
  FaPenNib,
  FaSwimmer,
  FaTheaterMasks,
  FaWalking,
} from "react-icons/fa";
import {
  FaBookOpen,
  FaCircleDot,
  FaHandsClapping,
  FaMasksTheater,
  FaMicrophoneLines,
  FaPaintbrush,
  FaScissors,
} from "react-icons/fa6";
import {
  GiCeremonialMask,
  GiCricketBat,
  GiDart,
  GiFlyingFlag,
  GiFountainPen,
  GiHighKick,
  GiHighPunch,
  GiKnot,
  GiMicrophone,
  GiMusicalNotes,
  GiMusicSpell,
  GiPush,
  GiRun,
  GiShuttlecock,
  GiSoccerBall,
  GiSprint,
  GiTargetShot,
  GiThrowingBall,
  GiVolleyballBall,
} from "react-icons/gi";
import { GrSwim } from "react-icons/gr";
import { IoIosMicrophone, IoLogoAngular } from "react-icons/io";
import {
  IoFootsteps,
  IoPencil,
  IoSparklesSharp,
  IoTabletLandscape,
} from "react-icons/io5";
import { MdGroups2, MdQuiz, MdSportsKabaddi } from "react-icons/md";

export const iconMap = {
  CiRoute,
  FaBook,
  FaBrain,
  FaCamera,
  FaChess,
  FaCircle,
  FaCompactDisc,
  FaHands,
  FaMicrophone,
  FaMusic,
  FaPalette,
  FaPenNib,
  FaTheaterMasks,
  FaBookOpen,
  FaCircleDot,
  FaHandsClapping,
  FaMasksTheater,
  FaMicrophoneLines,
  FaPaintbrush,
  FaScissors,
  GiCeremonialMask,
  GiCricketBat,
  GiDart,
  GiHighKick,
  GiHighPunch,
  GiKnot,
  GiMicrophone,
  GiMusicalNotes,
  GiMusicSpell,
  GiRun,
  GiShuttlecock,
  GiSoccerBall,
  GiSprint,
  GiTargetShot,
  GiVolleyballBall,
  IoIosMicrophone,
  IoFootsteps,
  IoPencil,
  IoSparklesSharp,
  IoTabletLandscape,
  MdGroups2,
  MdQuiz,
  MdSportsKabaddi,
  BsCameraReelsFill,
  GiFountainPen,
  IoLogoAngular,
  GiThrowingBall,
  FaSwimmer,
  GrSwim,
  FaWalking,
  GiFlyingFlag,
  GiPush,
};

export type IconName = keyof typeof iconMap;
